### ISSUE TITLE
Select DataFrame columns using a range of numbers.

### ISSUE THREAD

**Issue by kimjoaoun** [elixir-nx/explorer#161]
### Problem

I realised that it is currently impossible to select DataFrame columns using a range of values:

```elixir
iex>  Explorer.DataFrame.select(Explorer.Datasets.iris(), [1..3])

** (Protocol.UndefinedError) protocol String.Chars not implemented for 1..2 of type Range (a struct). This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
    (elixir 1.13.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.13.0) lib/string/chars.ex:22: String.Chars.to_string/1
    (explorer 0.1.0-dev) lib/explorer/data_frame.ex:1993: Explorer.DataFrame.maybe_raise_column_not_found/2
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (explorer 0.1.0-dev) lib/explorer/data_frame.ex:571: Explorer.DataFrame.select/3
```

or...

```elixir
iex > Explorer.DataFrame.select(Explorer.Datasets.iris(), 1..3)
** (Protocol.UndefinedError) protocol String.Chars not implemented for 1..2 of type Range (a struct). This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Float, Integer, List, NaiveDateTime, Time, URI, Version, Version.Requirement
    (elixir 1.13.0) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.13.0) lib/string/chars.ex:22: String.Chars.to_string/1
    (explorer 0.1.0-dev) lib/explorer/data_frame.ex:1993: Explorer.DataFrame.maybe_raise_column_not_found/2
    (elixir 1.13.0) lib/enum.ex:937: Enum."-each/2-lists^foreach/1-0-"/2
    (explorer 0.1.0-dev) lib/explorer/data_frame.ex:571: Explorer.DataFrame.select/3
iex(5)> Explorer.Datasets.iris |> Explorer.DataFrame.select(1..2)  
** (FunctionClauseError) no function clause matching in Explorer.DataFrame.select/3    
    
    The following arguments were given to Explorer.DataFrame.select/3:
    
        # 1
        #Explorer.DataFrame<
          [rows: 150, columns: 5]
          sepal_length float [5.1, 4.9, 4.7, 4.6, 5.0, "..."]
          sepal_width float [3.5, 3.0, 3.2, 3.1, 3.6, "..."]
          petal_length float [1.4, 1.4, 1.3, 1.5, 1.4, "..."]
          petal_width float [0.2, 0.2, 0.2, 0.2, 0.2, "..."]
          species string ["Iris-setosa", "Iris-setosa", "Iris-setosa",
           "Iris-setosa", "Iris-setosa", "..."]
        >
    
        # 2
        1..2
    
        # 3
        :keep 
    
    Attempted function clauses (showing 2 out of 2):
    
        def select(df, columns, keep_or_drop) when is_list(columns)
        def select(df, callback, keep_or_drop) when is_function(callback)
    
    (explorer 0.1.0-dev) lib/explorer/data_frame.ex:568: Explorer.DataFrame.select/3
```

### Possibility

I think that a possible implementation is to create a new `select/3` that accepts a range (`1..3`, for example) as the `columns` argument and returns a new DataFrame with the columns which the indexes fall within the range. That might be done using [Polars `select_by_range`](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#method.select_by_range) method.

```elixir
Explorer.DataFrame.select(df, %Range{} = columns, keep_or_drop)
```
### Desired result

```elixir
iex > Explorer.Datasets.iris |> Explorer.DataFrame.select(1..3)
#Explorer.DataFrame<
  [rows: 150, columns: 3]
  sepal_length float [5.1, 4.9, 4.7, 4.6, 5.0, "..."]
  sepal_width float [3.5, 3.0, 3.2, 3.1, 3.6, "..."]
  petal_length float [1.4, 1.4, 1.3, 1.5, 1.4, "..."]
>
```

### Other ecosystems:

This feature is currently available in:
R's `dplyr`
Python's `Pandas`
Julia's `DataFrames.jl`

**Comment by cigrainger** [comment]
I had this in an early version and removed it, and I don't remember why. I totally agree. I also think we should use `select_at_idx` so we can take a noncontinuous array of indices or a single index.

**Comment by kimjoaoun** [comment]
Can I try this one, @cigrainger?

**Comment by cigrainger** [comment]
Of course :)
