### ISSUE TITLE
:nif_not_loaded error when calling mutate_with with multiply

### ISSUE THREAD

**Issue by petrkozorezov** [elixir-nx/explorer#336]
I am trying to migrate existing code to explorer 0.3 and see the following error:
```elixir
Mix.install([{:explorer, "~> 0.3"}])

df = Explorer.DataFrame.new(a: [1, 2, 3])
Explorer.DataFrame.mutate_with(df, &[c: Explorer.Series.multiply(&1[:a], 1000)])
```
```
** (ErlangError) Erlang error: :nif_not_loaded
    :erlang.nif_error(:nif_not_loaded)
    (explorer 0.3.0) lib/explorer/polars_backend/native.ex:201: Explorer.PolarsBackend.Native.err/0
    (explorer 0.3.0) lib/explorer/polars_backend/data_frame.ex:322: anonymous fn/2 in Explorer.PolarsBackend.DataFrame.ungrouped_mutate_with/3
    (elixir 1.13.4) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (explorer 0.3.0) lib/explorer/polars_backend/data_frame.ex:321: Explorer.PolarsBackend.DataFrame.ungrouped_mutate_with/3
```

**Comment by josevalim** [comment]
This has been fixed in main. :)
