### ISSUE TITLE
Does not work with `livebook/livebook` docker image

### ISSUE THREAD

**Issue by sobolevn** [elixir-nx/explorer#44]
Image docs: https://github.com/livebook-dev/livebook#docker

Installation with

```elixir
Mix.install([
  {:explorer, "~> 0.1.0-dev", github: "amplifiedai/explorer"}
])
```

Fails with:

```
* Getting explorer (https://github.com/amplifiedai/explorer.git)
remote: Enumerating objects: 642, done.        
remote: Counting objects: 100% (642/642), done.        
remote: Compressing objects: 100% (402/402), done.        
remote: Total 642 (delta 400), reused 410 (delta 210), pack-reused 0        
origin/HEAD set to main
* Getting nx (https://github.com/elixir-nx/nx.git - origin/main)
remote: Enumerating objects: 9554, done.        
remote: Counting objects: 100% (1950/1950), done.        
remote: Compressing objects: 100% (922/922), done.        
remote: Total 9554 (delta 1173), reused 1671 (delta 965), pack-reused 7604        
Resolving Hex dependencies...
Dependency resolution completed:
New:
  rustler 0.22.0
  toml 0.5.2
* Getting rustler (Hex package)
* Getting toml (Hex package)
==> nx
Compiling 20 files (.ex)
Generated nx app
==> toml
Compiling 10 files (.ex)
Generated toml app
==> rustler
Compiling 7 files (.ex)
Generated rustler app
==> explorer
Compiling 14 files (.ex)
Compiling crate explorer in release mode (native/explorer)

== Compilation error in file lib/explorer/polars_backend/native.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.12.0) lib/system.ex:1041: System.cmd("cargo", ["rustc", "--release"], [cd: "/home/livebook/.cache/mix/installs/elixir-1.12.0-erts-12.0/b2b65fb8181f59bc8768c99cf9e3e5bc/deps/explorer/native/explorer", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/livebook/.cache/mix/installs/elixir-1.12.0-erts-12.0/b2b65fb8181f59bc8768c99cf9e3e5bc/_build/dev/lib/explorer/native/explorer"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    (rustler 0.22.0) lib/rustler/compiler.ex:27: Rustler.Compiler.compile_crate/2
    lib/explorer/polars_backend/native.ex:4: (module)
    (stdlib 3.15) erl_eval.erl:685: :erl_eval.do_apply/6
could not compile dependency :explorer, "mix compile" failed. You can recompile this dependency with "mix deps.compile explorer", update it with "mix deps.update explorer" or clean it with "mix deps.clean explorer"
```

I guess the solution is to provide a custom `livebook` image with extra dependecies.

**Comment by josevalim** [comment]
We will discuss adding this to Livebook, thank you!

**Comment by josevalim** [comment]
DIscussion here: https://github.com/livebook-dev/livebook/issues/543

**Comment by Nefcairon** [comment]
@sobolevn Do you have a working Dockerfile for using Explorer?

I'm desperate to create a Dockerfile for deployment at fly.io: https://elixirforum.com/t/deployment-of-nx-explorer-to-fly-io/43512/12

I hope you don't mind me asking here.

**Comment by sobolevn** [comment]
@Nefcairon yes, but it is big: https://github.com/livebook-dev/livebook/pull/544

I think that the core-team is working on solving this: https://github.com/livebook-dev/livebook/issues/543#issuecomment-932874524

**Comment by Nefcairon** [comment]
@sobolevn Thanks, using that Dockerfile I still get this error directly after it compiles explorer v0.1.0:

`
22:10:39.469 [warn]  The on_load function for module Elixir.Explorer.PolarsBackend.Native returned:
{:error,
 {:load_failed,
  'Failed to load NIF library: \'Error relocating /app/_build/prod/lib/explorer/priv/native/libexplorer.so: (null): initial-exec TLS resolves to dynamic definition in /app/_build/prod/lib/explorer/priv/native/libexplorer.so\''}}
`

Haven't you experienced the same?

**Comment by sobolevn** [comment]
Nope, this is new to me 😞
